// Automatically generated by ./configure 
#pragma once
// gcc
#define WITH_GCC 1
// gxx
#define WITH_GXX 1
// pkgconfig
#define WITH_PKGCONFIG 1
// install
#define WITH_INSTALL 1
// PIC
#define HAVE_PIC 1
// gnulib
#define WITH_GNULD 1
// __sync_32
#define HAVE_ATOMICS_32 1
// __sync_32
#define HAVE_ATOMICS_32_SYNC 1
// atomic_32
#define ATOMIC_OP32(OP1,OP2,PTR,VAL) __sync_ ## OP1 ## _and_ ## OP2(PTR, VAL)
// __sync_64
#define HAVE_ATOMICS_64 1
// __sync_64
#define HAVE_ATOMICS_64_SYNC 1
// atomic_64
#define ATOMIC_OP64(OP1,OP2,PTR,VAL) __sync_ ## OP1 ## _and_ ## OP2 (PTR, VAL)
// atomic_64
#define ATOMIC_OP(OP1,OP2,PTR,VAL) __sync_ ## OP1 ## _and_ ## OP2 (PTR, VAL)
// parseversion
#define RDKAFKA_VERSION_STR "0.8.3"
// perl
#define HAVE_PERL 1
